### PR TITLE
Add new settings variable for es6 compatibility

### PR DESCRIPTION
**Pull request by jamesloewen**
A very primitive change that uses a slightly tweaked template so that it is possible to import the generated file using es6 style imports.

### CODE REVIEW

**Comment by ierror** [comment]
Thank you! Do you have time adding test support for the JS_USE_ES6 option?

**Comment by jamesloewen** [comment]
I should be able to

**Comment by jamesloewen** [comment]
@ierror Any idea when you would be able to get this into a release?

**Comment by graingert** [comment]
@ierror @jamesloewen can we do this https://github.com/ierror/django-js-reverse/issues/61 intead?

**Comment by jamesloewen** [comment]
The feature you have requested is not mutually exclusive of this and a much larger change. So not instead. Since this is @ierror's package I won't comment on whether the other option is possible in addition.  If you want it, I recommend you build it as you can see that this PR has been open for 8 months and hasn't been merged yet.

In terms of using it, this code has now been in production since about a week after the PR went up and I can confirm that it works seamlessly with a webpack build (you may have to restart a watch build after running the command however).

**Comment by audiolion** [comment]
@ierror anything blocking this PR from being merged? It isn't a huge deal as it currently stands you can just `import '/path/to/reverse.js'` in your webpack config and it will attach it to the `window`, so in your javascript (react, vue, whatever) you can do `window.URLS[]`, this change would simply make it so you could `import { URLS } from 'path/to/reverse.js'` and `URLS[]` instead. But since there is no `window` in server side rendering, this would allow this package to be used for server side rendering of react/vue

**Comment by jamesloewen** [comment]
Looks like my merge at one point went awry. Closing and will reopen with a cleaned branch. Not sure what happened to the tests I wrote, will look into that

**Pull request closed without merging**
