### PR TITLE
move template logic to view

### PR DESCRIPTION
**Pull request by graingert**

### CODE REVIEW

**Comment by graingert** [comment]
For some reason I'm not getting emails about failing builds

**Comment by ierror** [comment]
@graingert strange - not sure if it's a misconfiguration on my side?

**Comment by graingert** [comment]
Probably just GDPR gone mad

**Comment by graingert** [comment]
@ierror can you also have a look at this one?

**Comment by graingert** [comment]
@ierror can you also have a look at this one?

**Comment by ierror** [comment]
@graingert Apologies for the late reply. Can you please briefly explain why the 

> package.json

 is needed? Otherwise the PR looks good and would be ready to merge. Thanks for that!

**Comment by graingert** [comment]
This is for the webpack/npm version

**Comment by ierror** [comment]
Is it okay for you if we remove the package.json for this PR and discuss the webpack/npm version separately?

**Comment by graingert** [comment]
> Is it okay for you if we remove the package.json for this PR and discuss the webpack/npm version separately?

No that's not ok. JavaScript shouldn't be generated programmatically

**Comment by ierror** [comment]
> > Is it okay for you if we remove the package.json for this PR and discuss the webpack/npm version separately?
> 
> No that's not ok. JavaScript shouldn't be generated programmatically

I agree but why should we mix refactoring "move template logic to view" with a new feature?

**Pull request merged**
