### PR TITLE
[READY] Added support to include only specific namespaces

### PR DESCRIPTION
**Pull request by BrnoPCmaniak**
Hi, I created this feature which allows you to choose just specific namespaces to show up in js reverser.

Unfortenutly I wasn't able to install phantomjs on my PC to run tests, but the tests should be fine and I debuged the code by hand in testing django project so it works for 100%(Just the code not tests).

### CODE REVIEW

**Comment by BrnoPCmaniak** [comment]
Sorry, I will try to get somewhere tests running, and then push fix here.

**Comment by BrnoPCmaniak** [comment]
Everything is now working.

**Comment by maackle** [comment]
I would love to see this feature merged in. I'll try this fork for now.

**Comment by ierror** [comment]
Sorry for the late reply. Thank you for contribution. I merged this PR, released v0.7.0  https://pypi.python.org/pypi/django-js-reverse/0.7.0 and added you to "AUTHORS"

**Pull request merged**
