### PR TITLE
Ensure consistent output ordering

### PR DESCRIPTION
**Pull request by PeterJCLaw**
Since the output file is one which we assume that people will put into version control, they're probably also going to want it to be stable and have CI validating it being up to date.

### CODE REVIEW

**Comment by graingert** [comment]
I think the easier fix is to use an OrderedDict in https://github.com/ierror/django-js-reverse/blob/master/django_js_reverse/core.py#L110-L121

**Comment by graingert** [comment]
eg:

```
def generate_json(default_urlresolver, script_prefix=None):
    if script_prefix is None:
        script_prefix = urlresolvers.get_script_prefix()
    urls = sorted(list(prepare_url_list(default_urlresolver)))

    return collections.OrderedDict(
        [
            (
                'urls',
                [
                    [
                        force_text(name),
                        [
                            [force_text(path), [force_text(arg) for arg in args]]
                            for path, args in patterns
                        ],
                    ]
                    for name, patterns in urls
                ],
            ),
            ('prefix', script_prefix),
        ]
    )
```

**Comment by PeterJCLaw** [comment]
> I think a neater fix is to use an OrderedDict in https://github.com/ierror/django-js-reverse/blob/master/django_js_reverse/core.py#L110-L121
> 
> because there's only 2 keys in the whole data structure

Yeah, I considered using an `OrderedDict` but decided against because `sort_keys` will ensure that the whole structure is always consistent, rather than making this a feature which the structure itself needs to maintain. I agree it doesn't feel obvious that the `_safe_json` helper handles this though.

**Comment by PeterJCLaw** [comment]
Anyway, 93dbc29 changes to using an `OrderedDict`.

**Comment by PeterJCLaw** [comment]
@graingert just so I know roughly what to expect -- what's the normal release cadence for this project?

**Pull request merged**
