### PR TITLE
Add JS_REVERSE_OUTPUT_PATH option

### PR DESCRIPTION
**Pull request by mjnaderi**
This is optional, and allows setting a different path for output of `collectstatic_js_reverse` other than `STATIC_ROOT`.

Reasons why this is useful:

1. `STATIC_ROOT` is used in production, so collectstatic_js_reverse doesn't help us in development. And we can't test it in development environment.
2. When using [ManifestStaticFilesStorage](https://docs.djangoproject.com/en/1.9/ref/contrib/staticfiles/#manifeststaticfilesstorage), Django's `collectstatic`, adds a hash to filenames before copying them to STATIC_ROOT. It helps us to apply far future Expires headers to the deployed files in `STATIC_ROOT`. When `collectstatic_js_reverse` writes to `STATIC_ROOT` its name will not be appended by a hash. But we can write `reverse.js` to some other directory (and we can add that directory to STATICFILES_DIRS), and Django's collectstaic will do the hashing stuff, etc with it.
3. Putting static files in `STATIC_ROOT`, using any method other than Django's `collectstatic` is discouraged by Django. There is a [warning](https://docs.djangoproject.com/en/1.9/ref/settings/#std:setting-STATIC_ROOT) about it in Django's Docs.

### CODE REVIEW

**Comment by mjnaderi** [comment]
Tests failed because pip [has dropped support for Python 3.2](https://github.com/pypa/pip/commit/b11cb019a47ff0cf3d8a37a0c89d8ae4cf25282f).

This option is very needed for us. If possible, please merge it. Thanks!

**Comment by ierror** [comment]
Thank you for you contribution! Could you please write a test for this feature? You can drop support for python 3.2 (tox.ini) - that's fine

**Comment by mjnaderi** [comment]
Ok, I will write a test as soon as possible.

**Comment by mjnaderi** [comment]
It is ready now.

**Comment by mjnaderi** [comment]
If there is any problem with my last commit, let me know so I can fix it. Thanks.

**Comment by ierror** [comment]
Thank you! I added you to AUTHORS

**Comment by mjnaderi** [comment]
Thanks. Is 0.7.0 going to be released?

**Comment by ierror** [comment]
ATM i also try to integrate https://github.com/ierror/django-js-reverse/pull/37 - Django 1.9 support. There are some strange "Connection refused" errors for the 1.9 tests i need to debug later on.

**Comment by ierror** [comment]
https://pypi.python.org/pypi/django-js-reverse/0.7.0 \o/ - thanks for your patience!

**Pull request merged**
